name: Build macOS

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.13.0
        pip install -r requirements.txt
    
    - name: Clean build directory
      run: |
        rm -rf dist build
        mkdir -p dist
    
    - name: Build macOS executable
      run: |
        pyinstaller --onefile --name backup-tool-macos backup_tool/cli.py
        mv dist/backup-tool-macos dist/backup-tool
    
    - name: Create app bundle
      run: |
        mkdir -p BackupTool.app/Contents/MacOS
        mkdir -p BackupTool.app/Contents/Resources
        cp macos/Info.plist BackupTool.app/Contents/
        cp dist/backup-tool BackupTool.app/Contents/MacOS/
        chmod +x BackupTool.app/Contents/MacOS/backup-tool
        zip -r dist/BackupTool.zip BackupTool.app
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backup-tool-macos
        path: |
          dist/backup-tool
          dist/BackupTool.zip
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/backup-tool
          dist/BackupTool.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}