name: Build Linux

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.13.0
        pip install -r requirements.txt
    
    - name: Clean build directory
      run: |
        rm -rf dist build
        mkdir -p dist
    
    - name: Build Linux executable
      run: |
        pyinstaller --onefile --name backup-tool-linux backup_tool/cli.py
        mv dist/backup-tool-linux dist/backup-tool
        chmod +x dist/backup-tool
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: backup-tool-linux
        path: dist/backup-tool
    
    - name: Create release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: 'dist/backup-tool'
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}